# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: locharve <locharve@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/06 11:10:47 by locharve          #+#    #+#              #
#    Updated: 2024/11/07 11:55:23 by locharve         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ffvii

SRC = main.cpp AMateria.cpp Ice.cpp Cure.cpp \
	Character.cpp MateriaSource.cpp

include ../ex00/Makefile