# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: locharve <locharve@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/05 12:47:46 by locharve          #+#    #+#              #
#    Updated: 2024/11/06 10:22:43 by locharve         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = set_the_world_on_fire

SRC = main.cpp Animal.cpp Brain.cpp Cat.cpp \
	Dog.cpp WrongAnimal.cpp WrongCat.cpp

include ../ex00/Makefile